source "https://rubygems.org"

# Ruby staff
gem "rake"
gem "rubocop"

# Static Site Generators
gem "jekyll"
gem "middleman"

# Xcode staff

# Generates swift playgrounds (https://github.com/segiddins/ThisCouldBeUsButYouPlaying)
gem "cocoapods-playgrounds"

# Cocoapods
gem "cocoapods"
