#!/usr/bin/env bash
#
# NAME
#   evernote_backup - Backups all evernote notes via AppleScrip
#
# SYNOPSIS
#   evernote_backup

echo "Starting to backup Evernote notes"

osascript -l JavaScript <<EOD
  // Get current date and make it proper (proper number of month, add leadings zeros)
  var currentDate = new Date()
  var properMonth = ("0" + (currentDate.getMonth() + 1)).slice(-2)
  var properDay = ("0" + currentDate.getDate()).slice(-2)
  var properMinutes = ("0" + currentDate.getMinutes()).slice(-2)
  var properSeconds = ("0" + currentDate.getSeconds()).slice(-2)

  var dateString = currentDate.getFullYear() + "_" + properMonth + "_" + properDay + "_"
    + currentDate.getHours() + "_" + properMinutes + "_" + properSeconds

  var app = Application.currentApplication()
  app.includeStandardAdditions = true
  var destination = app.pathTo('desktop') + "/evernote_notes_backup_" + dateString

  var evernote = Application('Evernote')
  var allNotes = evernote.findNotes()
  evernote.export(allNotes, {to: destination, format: "HTML"})
EOD

echo "All notes have been successfully backed up"
