#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Install Homebrew
./homebrew/install_homebrew.sh

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle --file="./homebrew/Brewfile"
brew bundle --file="./homebrew/Brewfile.cask"

# Set macOS defaults
echo "› Setting macOS defaults..."
./macos/set_defaults.sh

# find the installers and run them iteratively
echo "› Installing installers..."
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo "› Changing shell to zsh..."
chsh -s $(which zsh)
echo "› Successfully changed shell to zsh!"
