#!/usr/bin/env bash
#
# NAME
#   podforceupdate - Updates Pods with cache purged and DerivedData removed.
#
# SYNOPSIS
#   podforceupdate

rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
rm -rf "`pwd`/DerivedData/"
echo "Removed all folders"

echo "Running bundle exec pod update..."
bundle exec pod update
