#!/usr/bin/env bash
#
# NAME
#   xcodepurge - Removes cached pods and derived data folder.
#
# SYNOPSIS
#   xcodepurge

rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
rm -rf "`pwd`/DerivedData/"
