#!/usr/bin/env bash
#
# NAME
#   xcodepurge - Removes cached Pods and DerivedData folder.
#
# SYNOPSIS
#   xcodepurge

rm -rf "`pwd`/Pods/"
rm -rf "`pwd`/DerivedData/"

echo "Local Pods and DerivedData folder removed."
